##SEND FETCH SONGS REQUEST


POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "harman",
    "lastName": "muasa",
    "email": "harman.muasa@gmail.com",
    "password": "12345"
}



##SEND FETCH SONGS REQUEST 
# POST http://localhost:3000/songs
# Content-Type: application/json

# {
#     "title": "wahala",
#     "artists": ["Bien"],
#     "releasedDate": "2024-07-27",
#     "duration": "02:34"
# }

# ##Find SONGS Request
# send Request
# GET https://localhost:3000/songs/1

# ##Create new songs Request

# POST https://localhost:3000/songs

##update songs Request

# PUT https://localhost:3000/songs/1

# ## delete songs Request

# DELETE https://localhost:3000/songs/1